# Reference YAML
name: baseline_impressions # Note: will override saved models
mode: pretrain # pretrain, downstream, or evaluate
seed: 0 # Optional (Default: 0)
debug: False # Optional (Default: False)
batch_size: 32 # Optional (Default: 32)
num_workers: 4 # Optional (Default: 4)
checkpoint_path: checkpoints/ # Optional (Default: checkpoints/)
root_dir: data/ # Optional (Default: data/)

model_kwargs:
  image_encoder: resnet18
  hidden_dim: 1024
  out_dim: 512

criterion_kwargs:
  temperature: 0.1
  weight: 0.75

optimizer_kwargs:
  lr: 1.e-4 # Note: to ensure floats are processed correctly in scientific format, use a decimal seperator

train:
  frac: 0.1 # Optional: (Default: 1.0)
  max_epochs: 30 # Optional (Default: 1)
  text_req: impressions # Optional (Default: both)

downstream:
  frac: 0.01 # Optional: (Default: 1.0)
  dataset: MURA # MURA or CHEXPERT
  finetune: False # Optional (Default: True)
  max_epochs: 1 # Optional (Default: 1)
  
