# Reference YAML
name: test # Note: will override saved models
mode: pretrain # pretrain, finetune, or evaluate
seed: 0 # Optional (Default: 0)
debug: True # Optional (Default: False)
batch_size: 32 # Optional (Default: 32)
num_workers: 4 # Optional (Default: 4)
checkpoint_path: checkpoints/ # Optional (Default: checkpoints/)

model_kwargs:
  image_encoder: resnet18
  hidden_dim: 1024
  out_dim: 512

criterion_kwargs:
  temperature: 0.1
  weight: 0.75

optimizer_kwargs:
  lr: 1.e-6 # Note: to ensure floats are processed correctly in scientific format, use a decimal seperator

train:
  max_epochs: 3 # Optional (Default: 1)
  