# Reference YAML
name: test # Note: will override saved models
seed: 0 # Optional (Default: 0)
debug: True # Optional (Default: False)
wandb: # Optional
  save_dir: __pycache__/ # Optional (Default: __pycache__/)
dataset: 
  name: MURA
  kwargs: # Optional
    batch_size: 16
    num_workers: 8
model:
  name: test
  dir_path: checkpoints/ # Optional (Default: checkpoints/)
  kwargs: # Optional
    num_classes: 1
  criterion:
    name: bce_logits
    kwargs: # Optional
      reduction: mean
train:
  max_epochs: 1 # Optional (Default: 1)
  optimizer:
    name: adam
    kwargs: # Optional
      lr: 1.e-6 # Note: to ensure floats are processed correctly in scientific format, use a decimal seperator